In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("darkgrid")

In [ ]:
import os

In [ ]:
sales = pd.read_csv("/content/Sales_Data.csv")

In [ ]:
sales

,Unnamed: 0,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Hour
0,0,295665,Macbook Pro Laptop,1,1700.00,2019-12-30 00:01:00,"136 Church St, New York City, NY 10001",12,1700.00,New York City,0
1,1,295666,LG Washing Machine,1,600.00,2019-12-29 07:03:00,"562 2nd St, New York City, NY 10001",12,600.00,New York City,7
2,2,295667,USB-C Charging Cable,1,11.95,2019-12-12 18:21:00,"277 Main St, New York City, NY 10001",12,11.95,New York City,18
3,3,295668,27in FHD Monitor,1,149.99,2019-12-22 15:13:00,"410 6th St, San Francisco, CA 94016",12,149.99,San Francisco,15
4,4,295669,USB-C Charging Cable,1,11.95,2019-12-18 12:38:00,"43 Hill St, Atlanta, GA 30301",12,11.95,Atlanta,12
...,...,...,...,...,...,...,...,...,...,...,...
185945,13617,222905,AAA Batteries (4-pack),1,2.99,2019-06-07 19:02:00,"795 Pine St, Boston, MA 02215",6,2.99,Boston,19
185946,13618,222906,27in FHD Monitor,1,149.99,2019-06-01 19:29:00,"495 North St, New York City, NY 10001",6,149.99,New York City,19
185947,13619,222907,USB-C Charging Cable,1,11.95,2019-06-22 18:57:00,"319 Ridge St, San Francisco, CA 94016",6,11.95,San Francisco,18
185948,13620,222908,USB-C Charging Cable,1,11.95,2019-06-26 18:35:00,"916 Main St, San Francisco, CA 94016",6,11.95,San Francisco,18
185949,13621,222909,AAA Batteries (4-pack),1,2.99,2019-06-25 14:33:00,"209 11th St, Atlanta, GA 30301",6,2.99,Atlanta,14

In [ ]:
sales.shape

(185950, 11)

In [ ]:
sales.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185950 entries, 0 to 185949
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        185950 non-null  int64
 1   Order ID          185950 non-null  int64
 2   Product           185950 non-null  object
 3   Quantity Ordered  185950 non-null  int64
 4   Price Each        185950 non-null  float64
 5   Order Date        185950 non-null  object
 6   Purchase Address  185950 non-null  object
 7   Month             185950 non-null  int64
 8   Sales             185950 non-null  float64
 9   City              185950 non-null  object
 10  Hour              185950 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 65.1 MB

In [ ]:
sales.describe()

,Unnamed: 0,Order ID,Quantity Ordered,Price Each,Month,Sales,Hour
count,185950.000000,185950.000000,185950.000000,185950.000000,185950.000000,185950.000000,185950.000000
mean,8340.388475,230417.569379,1.124383,184.399735,7.059140,185.490917,14.413305
std,5450.554093,51512.737110,0.442793,332.731330,3.502996,332.919771,5.423416
min,0.000000,141234.000000,1.000000,2.990000,1.000000,2.990000,0.000000
25%,3894.000000,185831.250000,1.000000,11.950000,4.000000,11.950000,11.000000
50%,7786.000000,230367.500000,1.000000,14.950000,7.000000,14.950000,15.000000
75%,11872.000000,275035.750000,1.000000,150.000000,10.000000,150.000000,19.000000
max,25116.000000,319670.000000,9.000000,1700.000000,12.000000,3400.000000,23.000000

In [ ]:
sales.drop(columns="Unnamed: 0", inplace=True)

In [ ]:
sales.columns = ["order_id",
                 "product",
                 "quantity",
                 "price_each",
                 "order_date",
                 "purchase_address",
                 "month",
                 "sales_amount",
                 "city",
                 "hour"]

sales.columns

Index(['order_id', 'product', 'quantity', 'price_each', 'order_date',
       'purchase_address', 'month', 'sales_amount', 'city', 'hour'],
      dtype='object')

In [ ]:
print(sales[["product", "purchase_address", "city"]].apply(lambda x: x.str.startswith(" ")).sum())

print(sales[["product", "purchase_address", "city"]].apply(lambda x: x.str.endswith(" ")).sum())

product                  0
purchase_address         0
city                185950
dtype: int64
product             0
purchase_address    0
city                0
dtype: int64

In [ ]:
sales["city"] = sales["city"].str.lstrip()

In [ ]:
print(sales[["city"]].apply(lambda x: x.str.startswith(" ")).sum())

city    0
dtype: int64

In [ ]:
sales = sales.astype({"order_id":"int32",
                      "product":"category",
                      "quantity":"int8",
                      "order_date":"datetime64[ns]",
                      "purchase_address":"category",
                      "month":"int8",
                      "city":"category",
                      "hour":"int8"})

sales.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185950 entries, 0 to 185949
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          185950 non-null  int32
 1   product           185950 non-null  category
 2   quantity          185950 non-null  int8
 3   price_each        185950 non-null  float64
 4   order_date        185950 non-null  datetime64[ns]
 5   purchase_address  185950 non-null  category
 6   month             185950 non-null  int8
 7   sales_amount      185950 non-null  float64
 8   city              185950 non-null  category
 9   hour              185950 non-null  int8
dtypes: category(3), datetime64[ns](1), float64(2), int32(1), int8(3)
memory usage: 22.8 MB

In [ ]:
sales.isna().sum()

order_id            0
product             0
quantity            0
price_each          0
order_date          0
purchase_address    0
month               0
sales_amount        0
city                0
hour                0
dtype: int64

In [ ]:
sales[sales.duplicated()]

,order_id,product,quantity,price_each,order_date,purchase_address,month,sales_amount,city,hour
438,296081,Flatscreen TV,1,300.00,2019-12-30 16:52:00,"970 Sunset St, Austin, TX 73301",12,300.00,Austin,16
1727,297311,Bose SoundSport Headphones,1,99.99,2019-12-07 07:30:00,"858 Willow St, Los Angeles, CA 90001",12,99.99,Los Angeles,7
2812,298358,Apple Airpods Headphones,1,150.00,2019-12-04 15:57:00,"482 8th St, San Francisco, CA 94016",12,150.00,San Francisco,15
3119,298657,Lightning Charging Cable,1,14.95,2019-12-01 18:22:00,"428 12th St, Atlanta, GA 30301",12,14.95,Atlanta,18
3363,298883,Wired Headphones,1,11.99,2019-12-28 18:07:00,"516 Willow St, Los Angeles, CA 90001",12,11.99,Los Angeles,18
...,...,...,...,...,...,...,...,...,...,...
181613,218756,AAA Batteries (4-pack),1,2.99,2019-06-11 14:54:00,"362 Hickory St, Boston, MA 02215",6,2.99,Boston,14
181883,219007,AA Batteries (4-pack),1,3.84,2019-06-24 11:16:00,"42 8th St, Los Angeles, CA 90001",6,3.84,Los Angeles,11
183323,220392,Lightning Charging Cable,1,14.95,2019-06-08 17:13:00,"472 8th St, Portland, ME 04101",6,14.95,Portland,17
183826,220882,Lightning Charging Cable,1,14.95,2019-06-13 17:53:00,"588 Lake St, Boston, MA 02215",6,14.95,Boston,17
184691,221711,Bose SoundSport Headphones,1,99.99,2019-06-15 16:36:00,"139 West St, New York City, NY 10001",6,99.99,New York City,16

In [ ]:
sales.duplicated().sum()

np.int64(264)

In [ ]:
sales = sales.drop_duplicates().reset_index(drop=True)

In [ ]:
sales.shape[0]

185686

In [ ]:
sales = (sales.assign(
    date=sales["order_date"].dt.date,
    day_of_week=sales["order_date"].dt.dayofweek)
        )

sales.head()

,order_id,product,quantity,price_each,order_date,purchase_address,month,sales_amount,city,hour,date,day_of_week
0,295665,Macbook Pro Laptop,1,1700.00,2019-12-30 00:01:00,"136 Church St, New York City, NY 10001",12,1700.00,New York City,0,2019-12-30,0
1,295666,LG Washing Machine,1,600.00,2019-12-29 07:03:00,"562 2nd St, New York City, NY 10001",12,600.00,New York City,7,2019-12-29,6
2,295667,USB-C Charging Cable,1,11.95,2019-12-12 18:21:00,"277 Main St, New York City, NY 10001",12,11.95,New York City,18,2019-12-12,3
3,295668,27in FHD Monitor,1,149.99,2019-12-22 15:13:00,"410 6th St, San Francisco, CA 94016",12,149.99,San Francisco,15,2019-12-22,6
4,295669,USB-C Charging Cable,1,11.95,2019-12-18 12:38:00,"43 Hill St, Atlanta, GA 30301",12,11.95,Atlanta,12,2019-12-18,2

In [ ]:
desired_order = ["order_id",
                 "product",
                 "quantity",
                 "price_each",
                 "sales_amount",
                 "purchase_address",
                 "city",
                 "month",
                 "day_of_week",
                 "hour"]

sales = sales[desired_order]

sales.head()

,order_id,product,quantity,price_each,sales_amount,purchase_address,city,month,day_of_week,hour
0,295665,Macbook Pro Laptop,1,1700.00,1700.00,"136 Church St, New York City, NY 10001",New York City,12,0,0
1,295666,LG Washing Machine,1,600.00,600.00,"562 2nd St, New York City, NY 10001",New York City,12,6,7
2,295667,USB-C Charging Cable,1,11.95,11.95,"277 Main St, New York City, NY 10001",New York City,12,3,18
3,295668,27in FHD Monitor,1,149.99,149.99,"410 6th St, San Francisco, CA 94016",San Francisco,12,6,15
4,295669,USB-C Charging Cable,1,11.95,11.95,"43 Hill St, Atlanta, GA 30301",Atlanta,12,2,12